
package com.mark.hw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS", targetNamespace = "http://homeworkwsserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WS {


    /**
     * 
     * @param in0
     * @return
     *     returns com.mark.hw.ArrayOfCourseScore
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://homeworkwsserver")
    @RequestWrapper(localName = "getScoresByStudentNo", targetNamespace = "http://homeworkwsserver", className = "com.mark.hw.GetScoresByStudentNo")
    @ResponseWrapper(localName = "getScoresByStudentNoResponse", targetNamespace = "http://homeworkwsserver", className = "com.mark.hw.GetScoresByStudentNoResponse")
    public ArrayOfCourseScore getScoresByStudentNo(
        @WebParam(name = "in0", targetNamespace = "http://homeworkwsserver")
        String in0);

}
